spring:
  devtools:    livereload:      enabled: true
  mvc:    view:      prefix: /WEB-INF/jsp/
      suffix: .jsp
  application:
    name: rb-spring
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:rb-spring;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB      connection-timeout: 20000
    
server:
  port: 8080
  
logging:
  pattern:    console: test %-5level %logger{36} - %msg%n  level:
    root: ERROR
    com:
      mkyong: info
      zaxxer: DEBUG
    org.springframework: info    
    
    